#!/bin/bash

echo "📊 Hydro Time API - Database Schema"
echo "===================================="
echo ""
echo "Arquivo de Migration:"
echo "  prisma/migrations/init/migration.sql"
echo ""
echo "Server de Banco de Dados:"
echo "  PostgreSQL 16"
echo ""
echo "Provider:"
echo "  prisma/migrations/migration_lock.toml"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📌 TABELAS CRIADAS:"
echo ""
echo "1️⃣  User"
echo "   ├─ id (TEXT, PRIMARY KEY)"
echo "   ├─ email (TEXT, UNIQUE)"
echo "   ├─ name (TEXT)"
echo "   ├─ password (TEXT)"
echo "   ├─ createdAt (TIMESTAMP)"
echo "   └─ updatedAt (TIMESTAMP)"
echo ""
echo "2️⃣  UserSettings"
echo "   ├─ id (TEXT, PRIMARY KEY)"
echo "   ├─ userId (TEXT, FK → User)"
echo "   ├─ dailyGoalMl (INTEGER, default: 2500)"
echo "   ├─ reminderIntervalMinutes (INTEGER, default: 60)"
echo "   ├─ notificationsEnabled (BOOLEAN, default: true)"
echo "   ├─ language (TEXT, default: 'pt-BR')"
echo "   ├─ theme (TEXT, default: 'light')"
echo "   ├─ createdAt (TIMESTAMP)"
echo "   └─ updatedAt (TIMESTAMP)"
echo ""
echo "3️⃣  IntakeLog"
echo "   ├─ id (TEXT, PRIMARY KEY)"
echo "   ├─ userId (TEXT, FK → User)"
echo "   ├─ amountMl (INTEGER)"
echo "   ├─ timestamp (BIGINT)"
echo "   ├─ durationSeconds (INTEGER, default: 0)"
echo "   ├─ createdAt (TIMESTAMP)"
echo "   └─ updatedAt (TIMESTAMP)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔑 ÍNDICES CRIADOS:"
echo "   • User.email (UNIQUE)"
echo "   • UserSettings.userId (UNIQUE)"
echo "   • IntakeLog.userId"
echo "   • IntakeLog.timestamp"
echo ""
echo "🔗 RELACIONAMENTOS:"
echo "   • UserSettings → User (CASCADE DELETE)"
echo "   • IntakeLog → User (CASCADE DELETE)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Tudo pronto para usar com docker-compose!"
echo ""
echo "Para aplicar migrations ao banco:"
echo "  docker-compose up --build"
echo ""
echo "Para ver dados no Prisma Studio:"
echo "  docker-compose exec api npx prisma studio"
echo ""
